# Generated by Django 4.0 on 2021-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FLOOR', models.IntegerField(default=0)),
                ('UNIT_TYPE', models.CharField(max_length=20, null=True)),
                ('BATHROOMS', models.CharField(max_length=5, null=True)),
                ('UNIT', models.IntegerField(default=0)),
                ('INTERIOR', models.CharField(max_length=25, null=True)),
                ('TERRACE', models.CharField(max_length=25, null=True)),
                ('TOTAL', models.CharField(max_length=25, null=True)),
                ('PRICE', models.CharField(max_length=25, null=True)),
                ('FLOOR_PLANE', models.FileField(blank=True, upload_to='floor_plane/')),
            ],
        ),
    ]
