# Generated by Django 4.0 on 2022-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=150, verbose_name='Is a realtor'),
        ),
    ]
