# Generated by Django 4.0 on 2022-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Date and time')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Book an appointments',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
